### ISSUE TITLE
Problem with space characters appearing twice

### ISSUE THREAD

**Issue by sonntux** [Aeonos/mensaman#1]
In some cases it happens, that in the description text a space character is appearing twice instead once. Example from 2015-05-13 (Aktionsmenue):

"Natur gebratenes Kabeljaufilet  auf Senf-Dill-Soße, Salzkartoffeln und Gurkensalat 5,00 Euro"

Between Kabeljaufilet and Senf-Dill-Soße.

**Comment by Aeonos** [comment]
Has been fixed on latest push.
